### ISSUE TITLE
Fountain bug

### ISSUE THREAD

**Issue by lenara** [silantnode/warholsbot#6]
Bug found after spending /10 in the fountain, then clicking on /balance button.
The "thanks for your gift" message was displayed a second time, then came a message with the balance (new balance was only one Warhol less than previous balance), and the bot crashed.

Error message from console below:

    at Protocol._enqueue (/Users/lenara/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/Users/lenara/node_modules/mysql/lib/Connection.js:208:25)
    at AddToFountain (/Users/lenara/warholsbot-speculation/index.js:871:14)
    at /Users/lenara/warholsbot-speculation/index.js:674:9
    at Query._callback (/Users/lenara/warholsbot-speculation/index.js:861:16)
    at Query.Sequence.end (/Users/lenara/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query._handleFinalResultPacket (/Users/lenara/node_modules/mysql/lib/protocol/sequences/Query.js:137:8)
    at Query.EofPacket (/Users/lenara/node_modules/mysql/lib/protocol/sequences/Query.js:121:8)
    at Protocol._parsePacket (/Users/lenara/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/lenara/node_modules/mysql/lib/protocol/Parser.js:75:12)

**Comment by silantnode** [comment]
@lenara I forgot to add resets to the mode global variables. Added them and this has prevented quitting. But I am not 100% sure how this solved the problem... yet.
